apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deploy
  labels:
    purpose: test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      purpose: test
  template:
    metadata:
      labels:
        purpose: test  
    spec:
       containers:
         - image: nginx
           revisionHistoryLimit: 1
           ports:
             - containerPort: 80
           name: nginx-container  

---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    purpose: test
spec:
  containers:
    - image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080
      name: jenkins-contianer
      
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      name: nginx-front-end-port
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: jenkins-port
  selector:
    purpose: test
