apiVersion: v1
kind: Pod
metadata:
  name: argocd-pod
  labels:
    purpose: test
spec:
   contianers:
    - image: nginx
      ports:
        - contianerPort: 80
      name: nginx-container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      name: nginx-front-end-port
  selector:
    purpose: test
