apiVersion: v1
kind: ConfigMap
metadata:
  name: ssms-config
data:
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Express"
  init.sql: |
    IF DB_ID('mydb') IS NULL
    BEGIN
        CREATE DATABASE mydb;
    END
    GO

    USE mydb;
    GO

    IF OBJECT_ID('dbo.employees', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.employees (
            id INT IDENTITY(1,1) PRIMARY KEY,
            name NVARCHAR(100),
            created_date DATETIME DEFAULT GETDATE()
        );
    END
    GO
---
apiVersion: v1
kind: Secret
metadata:
  name: ssms-secret
data:
  MSSQL_SA_PASSWORD: YWRtaW4jMTIzCg==
type: Opaque  
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-table-job
spec:
  template:
    spec:
      containers:
        - name: ssms
          image: mcr.microsoft.com/mssql/server:2019-latest
          command: |
            - /bin/bash
            - -c
            - |
              /opt/mssql-tools18/bin/sqlcmd \
              -S ssms-svc \
              -U admin \
              -P "${MSSQL_SA_PASSWORD}" \
              -C \
              -i /sql/script/init.sql
            
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ssms-secret
                  key: MSSQL_SA_PASSWORD
          volumeMounts:
            - name: scritp-volume
              mountPath: /sql/script
      volumes:
        - name: scritp-volume
          configMap:
            name: ssms-config
---
apiVersion: v1
kind: Service
metadata:
  name: ssms-svc
spec:
  type: ExternalName
  externalName: database-1.cnsq28eocefn.eu-north-1.rds.amazonaws.com
  ports:
    - name: ssms-port
      port: 1433
      targetPort: 1433
      protocol: TCP
          
